"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.setPropertiesExpressions = exports.setKeyframeValuesToProperty = exports.removeTargetValues = exports.PropertyParser = exports.getTrackMatteTypeByName = exports.getPropertyListObject = exports.getLayerSettingsObject = exports.getKeyframeObjects = exports.getBlendingModeByName = exports.duplicateLayers = exports.copyToClipboard = exports.canSetTimeRemapEnabled = exports.addEffects = exports.addAdjustmentLayer = void 0;
var addAdjustmentLayer_1 = require("./addAdjustmentLayer");
Object.defineProperty(exports, "addAdjustmentLayer", { enumerable: true, get: function () { return addAdjustmentLayer_1.default; } });
var addEffects_1 = require("./addEffects");
Object.defineProperty(exports, "addEffects", { enumerable: true, get: function () { return addEffects_1.default; } });
var canSetTimeRemapEnabled_1 = require("./canSetTimeRemapEnabled");
Object.defineProperty(exports, "canSetTimeRemapEnabled", { enumerable: true, get: function () { return canSetTimeRemapEnabled_1.default; } });
var copyToClipboard_1 = require("./copyToClipboard");
Object.defineProperty(exports, "copyToClipboard", { enumerable: true, get: function () { return copyToClipboard_1.default; } });
var duplicateLayers_1 = require("./duplicateLayers");
Object.defineProperty(exports, "duplicateLayers", { enumerable: true, get: function () { return duplicateLayers_1.default; } });
var getBlendingModeByName_1 = require("./getBlendingModeByName");
Object.defineProperty(exports, "getBlendingModeByName", { enumerable: true, get: function () { return getBlendingModeByName_1.default; } });
var getKeyframeObjects_1 = require("./getKeyframeObjects");
Object.defineProperty(exports, "getKeyframeObjects", { enumerable: true, get: function () { return getKeyframeObjects_1.default; } });
var getLayerSettingsObject_1 = require("./getLayerSettingsObject");
Object.defineProperty(exports, "getLayerSettingsObject", { enumerable: true, get: function () { return getLayerSettingsObject_1.default; } });
var getPropertyListObject_1 = require("./getPropertyListObject");
Object.defineProperty(exports, "getPropertyListObject", { enumerable: true, get: function () { return getPropertyListObject_1.default; } });
var getTrackMatteTypeByName_1 = require("./getTrackMatteTypeByName");
Object.defineProperty(exports, "getTrackMatteTypeByName", { enumerable: true, get: function () { return getTrackMatteTypeByName_1.default; } });
var PropertyParser_1 = require("./PropertyParser");
Object.defineProperty(exports, "PropertyParser", { enumerable: true, get: function () { return PropertyParser_1.default; } });
var removeTargetValues_1 = require("./removeTargetValues");
Object.defineProperty(exports, "removeTargetValues", { enumerable: true, get: function () { return removeTargetValues_1.default; } });
var setKeyframeValuesToProperty_1 = require("./setKeyframeValuesToProperty");
Object.defineProperty(exports, "setKeyframeValuesToProperty", { enumerable: true, get: function () { return setKeyframeValuesToProperty_1.default; } });
var setPropertiesExpressions_1 = require("./setPropertiesExpressions");
Object.defineProperty(exports, "setPropertiesExpressions", { enumerable: true, get: function () { return setPropertiesExpressions_1.default; } });
